name: run main.py

on:
  schedule:
    - cron: '*/5 * * * *' # every 5 minutes

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: setup Python with cache
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: run main.py 
        run: |
          python main.py
      
      - name: commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update log

